---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install core apps
    package:
      name:
        - base-devel
        - neovim
        - rxvt-unicode
        - firefox
        - xf86-video-intel
        - nvidia
        - bluez
        - bluez-utils
        - slim
        - xorg
        - xorg-init
        - picom
        - dolphin
        - wallch
        - nitrogen
        - wallset
        - rofi
        - dunst
        - tint2
        - openbox
        - ttf-dejavu
        - ttf-liberation
        - i3-wm
        - gparted
        - parted
        - udiskie
        - rclone
        - kdeconnect
        - ufw
        - bacula
        - snort
        - clamav
        - rkhunter
        - gtile
        - piper
        - gcleaner
        - lmd
        - lynis
        - yubikey-manager
      state: latest
      update_cache: yes
    when: ansible ansible_distribution == "Arch"
